server:
  port:8080

spring:
  datasource:
    url: jdbc.oracle.thin:@dinkdb_medium?TNS_ADMIN=C:\SQLDEV\02_program\Wallet_DinkDB
    driver-class-name: oracle.jdbc.OracleDriver
    username: DA2605
    password: Data2605
  mybatis:
    mapper-locations: classpath:/mapper/**/*.xml
    type-aliases-package: kr.co.springbootex.ecommerce
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

      properties:
        hibernate:
          format_sql: true

